#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : keepassxc
Version  : 20.08.05
Release  : 20
URL      : file:///insilications/build/clearlinux/packages/keepassxc/keepassxc-20.08.05.zip
Source0  : file:///insilications/build/clearlinux/packages/keepassxc/keepassxc-20.08.05.zip
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0
Requires: keepassxc-bin = %{version}-%{release}
Requires: keepassxc-data = %{version}-%{release}
Requires: keepassxc-lib = %{version}-%{release}
BuildRequires : Linux-PAM-dev
BuildRequires : argon2-dev
BuildRequires : asciidoctor
BuildRequires : audit-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-gnome
BuildRequires : buildreq-golang
BuildRequires : buildreq-kde
BuildRequires : cairo-lib
BuildRequires : clr-desktop-defaults
BuildRequires : cups
BuildRequires : cups-filters
BuildRequires : cups-pk-helper
BuildRequires : dbus
BuildRequires : dbus-autostart
BuildRequires : dbus-bin
BuildRequires : dbus-broker
BuildRequires : dbus-config
BuildRequires : dbus-data
BuildRequires : dbus-dev
BuildRequires : dbus-extras
BuildRequires : dbus-glib-dev
BuildRequires : dbus-lib
BuildRequires : dbus-libexec
BuildRequires : dbus-license
BuildRequires : dbus-python
BuildRequires : dbus-python-dev
BuildRequires : dbus-services
BuildRequires : dconf
BuildRequires : dconf-dev
BuildRequires : evtest
BuildRequires : findutils
BuildRequires : fontconfig-data
BuildRequires : fontconfig-dev
BuildRequires : fontconfig-lib
BuildRequires : freetype-dev
BuildRequires : freetype-lib
BuildRequires : fuse
BuildRequires : gettext
BuildRequires : gettext-bin
BuildRequires : gjs
BuildRequires : glib
BuildRequires : glib-data
BuildRequires : glib-lib
BuildRequires : glib-networking
BuildRequires : gnome-keyring
BuildRequires : gobject-introspection-dev
BuildRequires : gtk+-data
BuildRequires : gtk+-lib
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : harfbuzz-dev
BuildRequires : harfbuzz-lib
BuildRequires : itstool
BuildRequires : keyutils-dev
BuildRequires : libICE-dev
BuildRequires : libSM-dev
BuildRequires : libX11
BuildRequires : libX11-data
BuildRequires : libX11-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86misc-dev libXxf86vm-dev
BuildRequires : libX11-lib
BuildRequires : libXScrnSaver-dev
BuildRequires : libXScrnSaver-lib
BuildRequires : libXau-dev
BuildRequires : libXau-lib
BuildRequires : libXcomposite-dev
BuildRequires : libXcursor-dev
BuildRequires : libXcursor-lib
BuildRequires : libXdamage-dev
BuildRequires : libXdamage-lib
BuildRequires : libXdmcp-dev
BuildRequires : libXdmcp-lib
BuildRequires : libXext-dev
BuildRequires : libXext-lib
BuildRequires : libXfixes-dev
BuildRequires : libXft-dev
BuildRequires : libXft-lib
BuildRequires : libXi-dev
BuildRequires : libXi-lib
BuildRequires : libXinerama-dev
BuildRequires : libXmu-dev
BuildRequires : libXpm-dev
BuildRequires : libXrandr-dev
BuildRequires : libXrender-dev
BuildRequires : libXrender-lib
BuildRequires : libXres-dev
BuildRequires : libXt-dev
BuildRequires : libXtst-dev
BuildRequires : libXtst-lib
BuildRequires : libXv-dev
BuildRequires : libXxf86misc-dev
BuildRequires : libXxf86vm-dev
BuildRequires : libXxf86vm-lib
BuildRequires : libcap
BuildRequires : libdbusmenu-dev
BuildRequires : libgcrypt-dev
BuildRequires : libgpg-error-dev
BuildRequires : libinput-data
BuildRequires : libinput-lib
BuildRequires : libinput-libexec
BuildRequires : libmicrohttpd
BuildRequires : libmicrohttpd-dev
BuildRequires : libpng-lib
BuildRequires : libseccomp-dev
BuildRequires : libsecret
BuildRequires : libsecret-bin
BuildRequires : libsecret-data
BuildRequires : libsecret-dev
BuildRequires : libsecret-lib
BuildRequires : libsecret-license
BuildRequires : libsecret-locales
BuildRequires : libsecret-man
BuildRequires : libsodium
BuildRequires : libsodium-dev
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : libxcb-lib
BuildRequires : libxkbcommon-dev
BuildRequires : libxml2-dev
BuildRequires : libxslt-bin
BuildRequires : mesa-dev
BuildRequires : mesa-lib
BuildRequires : mtdev
BuildRequires : ncurses-dev
BuildRequires : numlockx
BuildRequires : p11-kit-dev
BuildRequires : pango-lib
BuildRequires : perl(XML::Parser)
BuildRequires : pixman-lib
BuildRequires : pkg-config
BuildRequires : pkg-config-dev
BuildRequires : pkgconfig(accountsservice)
BuildRequires : pkgconfig(check)
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(gudev-1.0)
BuildRequires : pkgconfig(iso-codes)
BuildRequires : pkgconfig(libcanberra-gtk3)
BuildRequires : pkgconfig(libkeyutils)
BuildRequires : pkgconfig(libsodium)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pkgconfig(ncursesw)
BuildRequires : pkgconfig(quazip)
BuildRequires : pkgconfig(readline)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xau)
BuildRequires : pkgconfig(xcb)
BuildRequires : pkgconfig(xcb-xkb)
BuildRequires : pkgconfig(xcursor)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xkbcommon)
BuildRequires : pkgconfig(xmuu)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xtrans)
BuildRequires : pygobject
BuildRequires : pygobject-dev
BuildRequires : python3
BuildRequires : qrencode-dev
BuildRequires : qtbase-dev
BuildRequires : qtbase-dev mesa-dev
BuildRequires : qttools-extras
BuildRequires : qtx11extras-dev
BuildRequires : quazip
BuildRequires : quazip-dev
BuildRequires : quazip-staticdev
BuildRequires : readline-dev
BuildRequires : readline-staticdev
BuildRequires : setxkbmap
BuildRequires : systemd
BuildRequires : systemd-autostart
BuildRequires : systemd-bin
BuildRequires : systemd-config
BuildRequires : systemd-data
BuildRequires : systemd-dev
BuildRequires : systemd-extras
BuildRequires : systemd-lib
BuildRequires : systemd-license
BuildRequires : systemd-locales
BuildRequires : systemd-man
BuildRequires : systemd-services
BuildRequires : util-linux-dev
BuildRequires : vala-dev
BuildRequires : wayland-dev
BuildRequires : weston
BuildRequires : wmctrl
BuildRequires : xauth
BuildRequires : xauth-bin
BuildRequires : xcb-proto
BuildRequires : xclip
BuildRequires : xclip-bin
BuildRequires : xcursor-themes
BuildRequires : xdg-dbus-proxy
BuildRequires : xdg-desktop-portal
BuildRequires : xdg-desktop-portal-gtk
BuildRequires : xdg-desktop-portal-kde
BuildRequires : xdg-user-dirs
BuildRequires : xdg-user-dirs-gtk
BuildRequires : xdg-utils
BuildRequires : xdotool
BuildRequires : xdpyinfo
BuildRequires : xf86-input-evdev
BuildRequires : xf86-input-libinput
BuildRequires : xf86-video-amdgpu
BuildRequires : xf86-video-ati
BuildRequires : xf86-video-fbdev
BuildRequires : xf86-video-nouveau
BuildRequires : xf86-video-qxl
BuildRequires : xf86-video-vboxvideo
BuildRequires : xf86-video-vesa
BuildRequires : xfontsel
BuildRequires : xhost
BuildRequires : xinit
BuildRequires : xinput
BuildRequires : xkbcomp
BuildRequires : xkbcomp-bin
BuildRequires : xkeyboard-config
BuildRequires : xkill
BuildRequires : xmodmap
BuildRequires : xorg-fonts
BuildRequires : xorg-server
BuildRequires : xorg-server-bin
BuildRequires : xorg-server-dev
BuildRequires : xorgproto-dev
BuildRequires : xprop
BuildRequires : xrandr
BuildRequires : xrdb
BuildRequires : xrdp
BuildRequires : xrestop
BuildRequires : xsel
BuildRequires : xset
BuildRequires : xsetroot
BuildRequires : xterm
BuildRequires : xvfb-run
BuildRequires : xwd
BuildRequires : xwininfo
BuildRequires : zlib-dev
BuildRequires : zlib-staticdev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# <img src="https://keepassxc.org/images/keepassxc-logo.svg" width="40" height="40"/> KeePassXC
[![TeamCity Build Status](https://ci.keepassxc.org/app/rest/builds/buildType:\(project:KeepassXC\)/statusIcon)](https://ci.keepassxc.org/?guest=1)
[![codecov](https://codecov.io/gh/keepassxreboot/keepassxc/branch/develop/graph/badge.svg)](https://codecov.io/gh/keepassxreboot/keepassxc)
[![GitHub release](https://img.shields.io/github/release/keepassxreboot/keepassxc)](https://github.com/keepassxreboot/keepassxc/releases/)

%package bin
Summary: bin components for the keepassxc package.
Group: Binaries
Requires: keepassxc-data = %{version}-%{release}

%description bin
bin components for the keepassxc package.


%package data
Summary: data components for the keepassxc package.
Group: Data

%description data
data components for the keepassxc package.


%package lib
Summary: lib components for the keepassxc package.
Group: Libraries
Requires: keepassxc-data = %{version}-%{release}

%description lib
lib components for the keepassxc package.


%prep
%setup -q -n keepassxc-20.08.05
cd %{_builddir}/keepassxc-20.08.05

%build
unset http_proxy
unset https_proxy
unset no_proxy
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1596668260
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
## altflags_pgo content
## pgo generate
export PGO_GEN="-fprofile-generate=/var/tmp/pgo -fprofile-dir=/var/tmp/pgo -fprofile-abs-path -fprofile-update=atomic -fprofile-arcs -ftest-coverage --coverage -fprofile-partial-training"
export CFLAGS_GENERATE="-O3 -march=native -mtune=native -falign-functions=32 -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe $PGO_GEN"
export FCFLAGS_GENERATE="-O3 -march=native -mtune=native -falign-functions=32 -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe $PGO_GEN"
export FFLAGS_GENERATE="-O3 -march=native -mtune=native -falign-functions=32 -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe $PGO_GEN"
export CXXFLAGS_GENERATE="-O3 -march=native -mtune=native -falign-functions=32 -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -fvisibility-inlines-hidden -pipe $PGO_GEN"
export LDFLAGS_GENERATE="-O3 -march=native -mtune=native -falign-functions=32 -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe $PGO_GEN"
## pgo use
## -ffat-lto-objects -fno-PIE -fno-PIE -m64 -no-pie -fpic -fvisibility=hidden
## gcc: -feliminate-unused-debug-types -fipa-pta -flto=16 -Wno-error -Wp,-D_REENTRANT -fno-common
export PGO_USE="-fprofile-use=/var/tmp/pgo -fprofile-dir=/var/tmp/pgo -fprofile-abs-path -fprofile-correction -fprofile-partial-training"
export CFLAGS_USE="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe $PGO_USE"
export FCFLAGS_USE="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe $PGO_USE"
export FFLAGS_USE="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe $PGO_USE"
export CXXFLAGS_USE="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe $PGO_USE"
export LDFLAGS_USE="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe $PGO_USE"
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
#export CCACHE_DISABLE=1
## altflags_pgo end
export CFLAGS="${CFLAGS_GENERATE}"
export CXXFLAGS="${CXXFLAGS_GENERATE}"
export FFLAGS="${FFLAGS_GENERATE}"
export FCFLAGS="${FCFLAGS_GENERATE}"
export LDFLAGS="${LDFLAGS_GENERATE}"
%cmake .. -DCMAKE_BUILD_TYPE=Release \
-DCMAKE_C_FLAGS_RELEASE=-O3 \
-DCMAKE_C_FLAGS_RELWITHDEBINFO=-O3 \
-DCMAKE_CXX_FLAGS_RELEASE=-O3 \
-DCMAKE_CXX_FLAGS_RELWITHDEBINFO=-O3 \
-DCMAKE_VERBOSE_MAKEFILE=ON \
-DKEEPASSXC_BUILD_TYPE=Snapshot \
-DKEEPASSXC_DIST_TYPE=Other \
-DWITH_DEV_BUILD=ON \
-DWITH_GUI_TESTS=ON \
-DWITH_TESTS=ON \
-DWITH_XC_AUTOTYPE=ON \
-DWITH_XC_BROWSER=ON \
-DWITH_XC_DOCS=OFF \
-DWITH_XC_FDOSECRETS=ON \
-DWITH_XC_KEESHARE=ON \
-DWITH_XC_KEESHARE_SECURE=ON \
-DWITH_XC_NETWORKING=ON \
-DWITH_XC_SSHAGENT=ON \
-DWITH_XC_TOUCHID=OFF \
-DWITH_XC_UPDATECHECK=ON \
-DWITH_XC_YUBIKEY=OFF \
-DWITH_APP_BUNDLE=OFF
make  %{?_smp_mflags}  V=1 VERBOSE=1

export $(dbus-launch)
make test ARGS+="-E test\(cli\|gui\) --output-on-failure --verbose"
xvfb-run -e errors -a --server-args="-screen 0 1024x768x24" make test ARGS+="-R test\(cli\|gui\) --output-on-failure --verbose"
find . -type f -not -name '*.gcno' -delete -print
export CFLAGS="${CFLAGS_USE}"
export CXXFLAGS="${CXXFLAGS_USE}"
export FFLAGS="${FFLAGS_USE}"
export FCFLAGS="${FCFLAGS_USE}"
export LDFLAGS="${LDFLAGS_USE}"
%cmake .. -DCMAKE_BUILD_TYPE=Release \
-DCMAKE_C_FLAGS_RELEASE=-O3 \
-DCMAKE_C_FLAGS_RELWITHDEBINFO=-O3 \
-DCMAKE_CXX_FLAGS_RELEASE=-O3 \
-DCMAKE_CXX_FLAGS_RELWITHDEBINFO=-O3 \
-DCMAKE_VERBOSE_MAKEFILE=ON \
-DKEEPASSXC_BUILD_TYPE=Snapshot \
-DKEEPASSXC_DIST_TYPE=Other \
-DWITH_DEV_BUILD=ON \
-DWITH_GUI_TESTS=ON \
-DWITH_TESTS=ON \
-DWITH_XC_AUTOTYPE=ON \
-DWITH_XC_BROWSER=ON \
-DWITH_XC_DOCS=OFF \
-DWITH_XC_FDOSECRETS=ON \
-DWITH_XC_KEESHARE=ON \
-DWITH_XC_KEESHARE_SECURE=ON \
-DWITH_XC_NETWORKING=ON \
-DWITH_XC_SSHAGENT=ON \
-DWITH_XC_TOUCHID=OFF \
-DWITH_XC_UPDATECHECK=ON \
-DWITH_XC_YUBIKEY=OFF \
-DWITH_APP_BUNDLE=OFF
make  %{?_smp_mflags}  V=1 VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1596668260
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/keepassxc
/usr/bin/keepassxc-cli
/usr/bin/keepassxc-proxy

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.keepassxc.KeePassXC.desktop
/usr/share/icons/hicolor/256x256/apps/keepassxc.png
/usr/share/icons/hicolor/scalable/apps/keepassxc-locked.svg
/usr/share/icons/hicolor/scalable/apps/keepassxc-monochrome-dark-locked.svg
/usr/share/icons/hicolor/scalable/apps/keepassxc-monochrome-dark.svg
/usr/share/icons/hicolor/scalable/apps/keepassxc-monochrome-light-locked.svg
/usr/share/icons/hicolor/scalable/apps/keepassxc-monochrome-light.svg
/usr/share/icons/hicolor/scalable/apps/keepassxc-unlocked.svg
/usr/share/icons/hicolor/scalable/apps/keepassxc.svg
/usr/share/icons/hicolor/scalable/mimetypes/application-x-keepassxc.svg
/usr/share/keepassxc/icons/application/256x256/apps/keepassxc.png
/usr/share/keepassxc/translations/keepassx_ar.qm
/usr/share/keepassxc/translations/keepassx_bg.qm
/usr/share/keepassxc/translations/keepassx_ca.qm
/usr/share/keepassxc/translations/keepassx_cs.qm
/usr/share/keepassxc/translations/keepassx_da.qm
/usr/share/keepassxc/translations/keepassx_de.qm
/usr/share/keepassxc/translations/keepassx_en.qm
/usr/share/keepassxc/translations/keepassx_en_US.qm
/usr/share/keepassxc/translations/keepassx_es.qm
/usr/share/keepassxc/translations/keepassx_et.qm
/usr/share/keepassxc/translations/keepassx_fi.qm
/usr/share/keepassxc/translations/keepassx_fr.qm
/usr/share/keepassxc/translations/keepassx_hu.qm
/usr/share/keepassxc/translations/keepassx_id.qm
/usr/share/keepassxc/translations/keepassx_it.qm
/usr/share/keepassxc/translations/keepassx_ja.qm
/usr/share/keepassxc/translations/keepassx_ko.qm
/usr/share/keepassxc/translations/keepassx_lt.qm
/usr/share/keepassxc/translations/keepassx_nb.qm
/usr/share/keepassxc/translations/keepassx_nl_NL.qm
/usr/share/keepassxc/translations/keepassx_pl.qm
/usr/share/keepassxc/translations/keepassx_pt.qm
/usr/share/keepassxc/translations/keepassx_pt_BR.qm
/usr/share/keepassxc/translations/keepassx_pt_PT.qm
/usr/share/keepassxc/translations/keepassx_ro.qm
/usr/share/keepassxc/translations/keepassx_ru.qm
/usr/share/keepassxc/translations/keepassx_sk.qm
/usr/share/keepassxc/translations/keepassx_sv.qm
/usr/share/keepassxc/translations/keepassx_th.qm
/usr/share/keepassxc/translations/keepassx_tr.qm
/usr/share/keepassxc/translations/keepassx_uk.qm
/usr/share/keepassxc/translations/keepassx_zh_CN.qm
/usr/share/keepassxc/translations/keepassx_zh_TW.qm
/usr/share/keepassxc/wordlists/eff_large.wordlist
/usr/share/metainfo/org.keepassxc.KeePassXC.appdata.xml
/usr/share/mime-packages/keepassxc.xml

%files lib
%defattr(-,root,root,-)
/usr/lib64/keepassxc/libkeepassx-autotype-xcb.so
